from rest_framework import viewsets
from rest_framework.decorators import api_view
from rest_framework.response import Response
from django.conf import settings
import json

# Models aur Serializers import karna zaroori hai
from .models import Lead, NewsletterSubscriber
from .serializers import LeadSerializer, NewsletterSubscriberSerializer

# Try importing openai
try:
    import openai
except ImportError:
    openai = None

# --- 1. Lead ViewSet (Existing) ---
class LeadViewSet(viewsets.ModelViewSet):
    queryset = Lead.objects.all().order_by("-created_at")
    serializer_class = LeadSerializer

# --- 2. Newsletter Subscriber ViewSet (Existing) ---
class NewsletterSubscriberViewSet(viewsets.ModelViewSet):
    queryset = NewsletterSubscriber.objects.all().order_by('-subscribed_at')
    serializer_class = NewsletterSubscriberSerializer

# --- 3. AI Chatbot Logic (New) ---
@api_view(['POST'])
def chat_with_ai(request):
    user_message = request.data.get('message', '')
    history = request.data.get('history', []) 
    
    api_key = getattr(settings, 'OPENAI_API_KEY', None)
    
    if not api_key:
        return Response({"reply": "⚠️ Error: OpenAI API Key is missing in backend settings.", "action": None})

    client = openai.OpenAI(api_key=api_key)

    system_prompt = """
    You are 'XpertAI Assistant', a professional Sales AI for a Financial Consultancy firm.
    Your goal is to help users and politely collect their details (Name, Email, Service Interest).
    
    Services we offer: Virtual CFO, Audit, Taxation, Tech Services.

    RULES:
    1. Keep answers short (max 2 sentences).
    2. Be polite and professional.
    3. If the user is interested, ask for their Name and Email naturally.
    4. CRITICAL: If you have successfully collected the user's Name, Email, and Service, 
       you MUST output a hidden JSON block at the end of your reply like this:
       |||JSON:{"name": "Rahil", "email": "rahil@abc.com", "service": "Audit"}|||
    """

    messages = [{"role": "system", "content": system_prompt}] + history + [{"role": "user", "content": user_message}]

    try:
        response = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=messages,
            temperature=0.7
        )
        
        ai_reply = response.choices[0].message.content
        action = None

        if "|||JSON:" in ai_reply:
            parts = ai_reply.split("|||JSON:")
            public_reply = parts[0].strip()
            json_str = parts[1].split("|||")[0]
            
            try:
                lead_data = json.loads(json_str)
                Lead.objects.create(
                    name=lead_data.get('name', 'Unknown'),
                    email=lead_data.get('email', ''),
                    service=lead_data.get('service', 'General'),
                    message="Generated by AI Conversation",
                    source="chatbot"
                )
                action = "lead_captured"
            except Exception as e:
                print("JSON Parse Error:", e)
            
            ai_reply = public_reply

        return Response({"reply": ai_reply, "action": action})

    except Exception as e:
        return Response({"reply": f"AI Error: {str(e)}", "action": None})